package configuration

// default values for all configuration items
const (
	ENV_FILE = ".env"
	// HTTP - WEBSOCKET
	HTTP_LOCAL_SERVER_LOCATION_DEFAULT    = "0.0.0.0:8080"
	HTTP_LOCAL_HTMLSERVER_ENABLED_DEFAULT = true
	HTTP_TLS_CERT_FILE_LOCATION_DEFAULT   = ""
	HTTP_TLS_KEY_FILE_LOCATION_DEFAULT    = ""
	HTTP_GIN_IS_DEBUG_DEFAULT             = true
	// WEBRTC
	RTC_VIDEO_TRACKS_RECEIVE_PORT_DEFAULT  uint16 = 5004
	RTC_AUDIO_TRACKS_RECEIVE_PORT_DEFAULT  uint16 = 5005
	RTC_RECEIVE_RTP_BUFFSIZE_DEFAULT       uint16 = 1200
	RTC_VIDEO_CODEC_DEFAULT                       = "video/VP8"
	RTC_AUDIO_CODEC_DEFAULT                       = "audio/opus"
	RTC_DISCONNECT_TIMEOUT_SECONDS_DEFAULT uint   = 10
	RTC_FAILED_TIMEOUT_SECONDS_DEFAULT     uint   = 30
	RTC_KEEPALIVE_INTERVAL_SECONDS_DEFAULT uint   = 2
	// SERVER PREFS
	SERVER_EPHEMERAL_UDP_PORT_RANGE_MIN_DEFAULT uint16 = 4069
	SERVER_EPHEMERAL_UDP_PORT_RANGE_MAX_DEFAULT uint16 = 65535
	SERVER_NAT_1TO1_IPS_DEFAULT                        = ""
)
